package com.pixelhaven.servlet;

import com.pixelhaven.dao.PhoneRepository;
import com.pixelhaven.model.PixelPhone;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.Part;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@WebServlet("/addProduct")
@MultipartConfig(
        fileSizeThreshold = 1024 * 1024 * 2, // 2MB
        maxFileSize = 1024 * 1024 * 10,      // 10MB
        maxRequestSize = 1024 * 1024 * 50    // 50MB
)
public class AddProductServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // 1. Get the list of existing series from the database
        List<String> seriesList = PhoneRepository.getAllSeries();

        // 2. Send it to the JSP
        req.setAttribute("seriesList", seriesList);

        req.getRequestDispatcher("addProduct.jsp").forward(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            // ============================
            // 1. GET BASIC INFO
            // ============================
            String id = req.getParameter("id");
            String name = req.getParameter("name");
            String series = req.getParameter("series");
            String description = req.getParameter("description");

            // ============================
            // 2. PROCESS STORAGE & PRICES
            // ============================
            // getParameterValues returns array of all inputs with that name
            String[] sizeInputs = req.getParameterValues("storageSize");
            String[] priceInputs = req.getParameterValues("storagePrice");

            List<String> storageSizes = new ArrayList<>();
            List<Double> storagePrices = new ArrayList<>();

            if (sizeInputs != null && priceInputs != null) {
                for (int i = 0; i < sizeInputs.length; i++) {
                    storageSizes.add(sizeInputs[i]);
                    // Convert string price to double
                    storagePrices.add(Double.parseDouble(priceInputs[i]));
                }
            }

            // Determine base price (lowest price in the list)
            double basePrice = storagePrices.stream().mapToDouble(v -> v).min().orElse(0.0);


            // ============================
            // 3. PROCESS IMAGES & COLORS
            // ============================
            // Setup upload path
            String uploadPath = getServletContext().getRealPath("") + File.separator + "images";
            File uploadDir = new File(uploadPath);
            if (!uploadDir.exists()) uploadDir.mkdir();

            // A. Save Default Image
            String defaultImgName = saveFile(req.getPart("defaultImage"), uploadPath);

            // B. Process Dynamic Colors and their Images
            String[] colorNamesInput = req.getParameterValues("colorName");
            String[] colorHexInput = req.getParameterValues("colorHex");
            // Get total count of color rows attempted generated by JS
            int colorCountTotal = Integer.parseInt(req.getParameter("colorCount"));

            List<String> colorNames = new ArrayList<>();
            List<String> colorHexes = new ArrayList<>();
            List<String> colorImages = new ArrayList<>();

            // We loop through input arrays for names/hexes
            if (colorNamesInput != null) {
                int processedIndex = 0;
                // We loop up to the total count JS created to find the matching file parts
                for (int i = 0; i < colorCountTotal; i++) {
                    // Look for part named colorImg0, colorImg1, etc.
                    Part colorPart = req.getPart("colorImg" + i);
                    // If this part exists (it wasn't deleted in UI) add data to lists
                    if (colorPart != null) {
                        colorNames.add(colorNamesInput[processedIndex]);
                        colorHexes.add(colorHexInput[processedIndex]);
                        // Save file and add filename to list
                        colorImages.add(saveFile(colorPart, uploadPath));
                        processedIndex++;
                    }
                }
            }

            // ============================
            // 4. CREATE & SAVE PHONE
            // ============================
            PixelPhone newPhone = new PixelPhone(
                    id, name, description, basePrice, defaultImgName, series,
                    colorHexes, colorNames, colorImages,
                    storageSizes, storagePrices,
                    // Placeholder data for specs - you could add inputs for these later
                    "<ul><li>Specs coming soon</li></ul>",
                    "<ul><li>Dimensions coming soon</li></ul>",
                    "<ul><li>Battery info coming soon</li></ul>",
                    "<ul><li>Camera info coming soon</li></ul>",
                    "<ul><li>Front camera info coming soon</li></ul>"
            );

            PhoneRepository.addPhone(newPhone);

            // Redirect back to dashboard with success
            resp.sendRedirect("admin.jsp?msg=ProductAdded");

        } catch (Exception e) {
            e.printStackTrace();
            resp.getWriter().println("Error adding product: " + e.getMessage());
        }
    }

    // Helper method to save a file part and return the filename
    private String saveFile(Part part, String uploadPath) throws IOException {
        if (part == null || part.getSize() == 0) return "default_placeholder.jpg";
        String fileName = getFileName(part);
        part.write(uploadPath + File.separator + fileName);
        return fileName;
    }

    // Utility to extract filename from upload part header
    private String getFileName(final Part part) {
        for (String content : part.getHeader("content-disposition").split(";")) {
            if (content.trim().startsWith("filename")) {
                return content.substring(content.indexOf('=') + 1).trim().replace("\"", "");
            }
        }
        return "unknownfile_" + System.currentTimeMillis() + ".jpg";
    }
}